# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\16639\Documents\WorkSpace\MyTools\View\WebDictionaryView.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WebDictionaryView(object):
    def setupUi(self, WebDictionaryView):
        WebDictionaryView.setObjectName("WebDictionaryView")
        WebDictionaryView.resize(1010, 770)
        self.gridLayout_3 = QtWidgets.QGridLayout(WebDictionaryView)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(WebDictionaryView)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(WebDictionaryView)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(WebDictionaryView)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 2)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(2, 3)

        self.retranslateUi(WebDictionaryView)
        QtCore.QMetaObject.connectSlotsByName(WebDictionaryView)

    def retranslateUi(self, WebDictionaryView):
        _translate = QtCore.QCoreApplication.translate
        WebDictionaryView.setWindowTitle(_translate("WebDictionaryView", "Form"))
        self.pushButton.setText(_translate("WebDictionaryView", "翻译"))
        self.pushButton.setShortcut(_translate("WebDictionaryView", "Ctrl+Return"))
        self.groupBox_2.setTitle(_translate("WebDictionaryView", "网络释义"))
        self.groupBox.setTitle(_translate("WebDictionaryView", "英汉互译--自动检测"))
